#!/bin/bash

# --- Configuration ---
WARP_CONTAINER="/users/artem.kushner/warp_aretomo1.0.0_cuda11.8_glibc2.31.sif"
PROJECT_BIND="/scratch-cbe/users/$USER/cryoboost_projects:/project"
DATA_BIND="/users/artem.kushner/dev/001_CopiaTestSet/:/users/artem.kushner/dev/001_CopiaTestSet/:ro"

echo "--- WarpTools Adapter Activated ---" >&2
echo "Job Directory: $(pwd)" >&2
echo "Executing command inside warp.sif: WarpTools $*" >&2
echo "---------------------------------" >&2

# Execute the final Warp command inside the dedicated warp.sif container
apptainer run \
    --nv \
    -B "${PROJECT_BIND}" \
    -B "${DATA_BIND}" \
    --env PATH="/opt/AreTomo2:$PATH" \
    --pwd "$(pwd)" \
    "${WARP_CONTAINER}" \
    WarpTools "$@"
